# Cau hinh train YOLO OCR (Nhan dien ky tu)
model: yolov8n.pt
data: data/char_detection/data.yaml
imgsz: 320 # Ky tu nho nen chi can 320 la du
epochs: 100
batch: 32
project: experiments/char_ocr
name: v1
